# Pixel Software Design � Copyright 2026
#!/usr/bin/env python3
"""
RobotFirewall — Générateur et applicateur de règles PF pour robots PixelOS.

Isolation réseau stricte :
  - Le robot ne parle QU'à l'orchestrateur (API 8080, MQTT 1883, PixKey 8443)
  - Trafic PixNet P2P autorisé uniquement via WireGuard (wg0)
  - Bus IPC local (9101, loopback)
  - Tout le reste est DROP + log
  - Rate limiting anti-brute-force
  - PixDefend blocklist dynamique
"""

import os
import json
import subprocess
import socket
from datetime import datetime
from pathlib import Path
from typing import Optional

PF_CONF_PATH = "/etc/pf.conf"
PF_ANCHOR = "pixelos/robot"

FIREWALL_DIR = "/var/db/pixelos/firewall"
STATE_FILE = "firewall_state.json"

DEFAULT_ROBOT_RULES = """
# Generated by RobotFirewall — {ts}
# Isolation robot PixelOS

robot_if = "{iface}"
wg_if    = "wg0"
orch_ip  = "{orch_ip}"
orch_net = "{orch_net}"

set block-policy drop
set loginterface egress
set skip on lo

block in log all
block out log all

pass quick on lo all
pass in  on $wg_if all keep state
pass out on $wg_if all keep state

# Orchestrateur
pass out on $robot_if proto tcp from any to $orch_ip port {port_api} keep state
pass out on $robot_if proto tcp from any to $orch_ip port {port_mqtt} keep state
pass in  on $robot_if proto tcp from $orch_ip to any port {port_api} keep state
pass in  on $robot_if proto tcp from $orch_ip to any port {port_mqtt} keep state

# PixKey Auth
pass out on $robot_if proto tcp from any to $orch_ip port {port_pixkey} keep state
pass in  on $robot_if proto tcp from $orch_ip to any port {port_pixkey} keep state

# PixNet P2P (découverte UDP)
pass out on $robot_if proto udp from any to $orch_net port {port_pixnet} keep state
pass in  on $robot_if proto udp from $orch_net to any port {port_pixnet} keep state

# DHCP
pass out on $robot_if proto udp to port {port_dhcp} keep state

# DNS .pixel
pass out on $robot_if proto {{ tcp, udp }} to $orch_ip port {port_dns} keep state

# NTP
pass out on $robot_if proto udp to any port {port_ntp} keep state

# ICMP (orchestrateur seulement)
pass in  on $robot_if proto icmp from $orch_ip icmp-type echoreq
pass out on $robot_if proto icmp icmp-type echoreq

# Bus IPC local
pass in  on lo proto tcp to port {port_ipc}

# PixDefend
table <pixos_blocklist> persist
block in quick from <pixos_blocklist> to any

# Rate limiting SSH
table <bruteforce> persist
block quick from <bruteforce>
pass in on $robot_if proto tcp to port 22 \\
    keep state (max-src-conn 3, max-src-conn-rate 2/60, \\
    overload <bruteforce> flush global)

# Anti-spoofing
block in quick from urpf-failed
block in quick on $robot_if proto tcp flags FUP
block in quick on $robot_if proto tcp flags /SFUP

block return out log on $robot_if from any to any
"""


class RobotFirewall:
    def __init__(self, orch_ip: str = "10.0.0.1"):
        self.orch_ip = orch_ip
        self.orch_net = "10.0.0.0/24"
        self.iface = self._detect_interface()
        self._ensure_dirs()
        self._load_state()

    def _ensure_dirs(self):
        Path(FIREWALL_DIR).mkdir(parents=True, exist_ok=True)

    def _path(self, name):
        return str(Path(FIREWALL_DIR) / name)

    def _load_state(self):
        p = self._path(STATE_FILE)
        if os.path.exists(p):
            try:
                self.state = json.loads(Path(p).read_text())
            except Exception:
                self.state = {}
        else:
            self.state = {}

    def _save_state(self):
        Path(self._path(STATE_FILE)).write_text(json.dumps(self.state, indent=2))

    def _detect_interface(self) -> str:
        for iface in ["vio0", "eth0", "enp0s3", "en0", "wlan0"]:
            try:
                r = subprocess.run(
                    ["ifconfig", iface],
                    capture_output=True, text=True, timeout=5,
                )
                if r.returncode == 0 and "inet" in r.stdout:
                    return iface
            except Exception:
                pass
        return "vio0"

    def generate_rules(self) -> str:
        now = datetime.now().isoformat()
        ports = {
            "port_api": 8080, "port_mqtt": 1883, "port_pixkey": 8443,
            "port_pixnet": 8337, "port_ipc": 9101, "port_dns": 5300,
            "port_ntp": 123, "port_dhcp": 67,
        }
        return DEFAULT_ROBOT_RULES.format(
            ts=now, iface=self.iface, orch_ip=self.orch_ip,
            orch_net=self.orch_net, **ports,
        )

    def apply(self, pf_conf_path: str = PF_CONF_PATH) -> dict:
        rules = self.generate_rules()
        try:
            Path(pf_conf_path).write_text(rules)
            r = subprocess.run(
                ["pfctl", "-vnf", pf_conf_path],
                capture_output=True, text=True, timeout=10,
            )
            if r.returncode != 0:
                return {"status": "error", "error": r.stderr[:500]}

            r2 = subprocess.run(
                ["pfctl", "-f", pf_conf_path],
                capture_output=True, text=True, timeout=10,
            )
            ok = r2.returncode == 0
            self.state = {
                "applied_at": datetime.now().isoformat(),
                "iface": self.iface,
                "orch_ip": self.orch_ip,
                "rules_valid": True,
                "pfctl_output": r.stdout[:200] if ok else r2.stderr[:200],
            }
            self._save_state()
            return {"status": "ok" if ok else "error",
                    "output": r.stdout[:200] if ok else r2.stderr[:200]}
        except Exception as e:
            return {"status": "error", "error": str(e)}

    def status(self) -> dict:
        try:
            r = subprocess.run(
                ["pfctl", "-s", "info"],
                capture_output=True, text=True, timeout=5,
            )
            running = "Enabled" in r.stdout
        except Exception:
            running = False
        return {
            "firewall_running": running,
            "interface": self.iface,
            "orchestrator": self.orch_ip,
            "last_applied": self.state.get("applied_at", ""),
            "state": self.state,
        }

    def block_ip(self, ip: str) -> dict:
        try:
            r = subprocess.run(
                ["pfctl", "-t", "pixos_blocklist", "-T", "add", ip],
                capture_output=True, text=True, timeout=5,
            )
            return {"status": "ok" if r.returncode == 0 else "error",
                    "ip": ip, "output": r.stdout[:200]}
        except Exception as e:
            return {"status": "error", "error": str(e)}

    def unblock_ip(self, ip: str) -> dict:
        try:
            r = subprocess.run(
                ["pfctl", "-t", "pixos_blocklist", "-T", "delete", ip],
                capture_output=True, text=True, timeout=5,
            )
            return {"status": "ok" if r.returncode == 0 else "error",
                    "ip": ip}
        except Exception as e:
            return {"status": "error", "error": str(e)}

    def get_blocklist(self) -> list:
        try:
            r = subprocess.run(
                ["pfctl", "-t", "pixos_blocklist", "-T", "show"],
                capture_output=True, text=True, timeout=5,
            )
            return [ip for ip in r.stdout.strip().split("\n") if ip]
        except Exception:
            return []

    def stats(self) -> dict:
        try:
            r = subprocess.run(
                ["pfctl", "-s", "info"],
                capture_output=True, text=True, timeout=5,
            )
            info = r.stdout[:500]
        except Exception:
            info = ""
        return {
            "status": self.status(),
            "blocklist_size": len(self.get_blocklist()),
            "rules_generated": True,
            "pf_info": info,
        }
